version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    volumes:
      - .:/app  # Syncs code changes
    ports:
      - "8000:8000"  # Exposes Django on localhost:8000
    environment:
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    command: /app/start.sh
    links:
      - db:db
  db:
    image: postgres:15
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

